/**
 * Threshold Decryption Utility – Phase 4
 *
 * Implements:
 *  - Lagrange interpolation over integers (Shamir secret reconstruction)
 *  - Paillier homomorphic decryption using the reconstructed lambda (λ)
 *
 * All arithmetic is done with BigInt to handle 2048-bit numbers correctly.
 */

// ---------------------------------------------------------------------------
// BigInt helpers
// ---------------------------------------------------------------------------

/**
 * Fast modular exponentiation: (base ^ exp) mod modulus
 */
function modPow(base, exp, modulus) {
  if (modulus === 1n) return 0n;
  let result = 1n;
  base = ((base % modulus) + modulus) % modulus;
  while (exp > 0n) {
    if (exp & 1n) result = (result * base) % modulus;
    exp >>= 1n;
    base = (base * base) % modulus;
  }
  return result;
}

/**
 * Extended Euclidean Algorithm – returns { gcd, x, y } such that a*x + b*y = gcd
 */
function extendedGcd(a, b) {
  if (b === 0n) return { gcd: a, x: 1n, y: 0n };
  const { gcd, x, y } = extendedGcd(b, a % b);
  return { gcd, x: y, y: x - (a / b) * y };
}

/**
 * Modular multiplicative inverse: a^-1 mod m
 * Throws if inverse does not exist.
 */
function modInverse(a, m) {
  const { gcd, x } = extendedGcd(((a % m) + m) % m, m);
  if (gcd !== 1n) throw new Error('Modular inverse does not exist');
  return ((x % m) + m) % m;
}

// ---------------------------------------------------------------------------
// Shamir Secret Reconstruction (Lagrange interpolation at x = 0)
// ---------------------------------------------------------------------------

/**
 * Reconstruct the Shamir secret from a threshold number of shares.
 *
 * Each share is an object with numeric `x`, string `y`, and optionally
 * string `prime` fields (as stored in the trustee_shares/*.json files after
 * being decrypted by decryptShareY).
 *
 * When `prime` is present (generated by the fixed backend), uses modular
 * Lagrange interpolation over GF(prime) — information-theoretically secure.
 * Falls back to rational interpolation for legacy shares without a prime.
 *
 * @param {Array<{x: number, y: string, prime?: string}>} shares
 * @returns {BigInt} reconstructed secret (lambda)
 */
export function reconstructSecret(shares) {
  if (shares.length < 2) throw new Error('Need at least 2 shares to reconstruct');

  // Convert to BigInt pairs
  const pts = shares.map(s => ({ x: BigInt(s.x), y: BigInt(s.y) }));

  // --- Modular path (secure, preferred) ---
  const primeStr = shares[0].prime;
  if (primeStr) {
    const p = BigInt(primeStr);
    let secret = 0n;

    for (let i = 0; i < pts.length; i++) {
      let num = 1n;
      let den = 1n;

      for (let j = 0; j < pts.length; j++) {
        if (i === j) continue;
        num = (num * ((0n - pts[j].x + p) % p)) % p;
        den = (den * ((pts[i].x - pts[j].x + p) % p)) % p;
      }

      const lagrange = (num * modInverse(den, p)) % p;
      secret = (secret + pts[i].y * lagrange) % p;
    }

    return secret;
  }

  // --- Legacy rational path (kept for backward compatibility) ---
  // Lagrange interpolation at x = 0 over rationals, accumulated as fractions
  // f(0) = Σ_i  y_i * Π_{j≠i} (0 - x_j) / (x_i - x_j)
  let numeratorAcc = 0n;
  let denominatorAcc = 1n;

  for (let i = 0; i < pts.length; i++) {
    let num = pts[i].y;   // y_i
    let den = 1n;

    for (let j = 0; j < pts.length; j++) {
      if (i === j) continue;
      num *= (0n - pts[j].x);   // × (-x_j)
      den *= (pts[i].x - pts[j].x); // × (x_i - x_j)
    }

    // Accumulate: acc = acc + num/den
    // Using cross-multiplication: (a/b) + (c/d) = (a*d + c*b) / (b*d)
    numeratorAcc = numeratorAcc * den + num * denominatorAcc;
    denominatorAcc = denominatorAcc * den;
  }

  // The secret is the integer result of numeratorAcc / denominatorAcc
  if (denominatorAcc === 0n) throw new Error('Degenerate shares: denominator is zero');
  if (numeratorAcc % denominatorAcc !== 0n) {
    throw new Error('Share reconstruction yielded non-integer result – shares may be corrupt');
  }

  return numeratorAcc / denominatorAcc;
}

// ---------------------------------------------------------------------------
// Paillier Decryption
// ---------------------------------------------------------------------------

/**
 * Paillier L-function: L(u) = (u - 1) / n
 */
function L(u, n) {
  return (u - 1n) / n;
}

/**
 * Decrypt a Paillier ciphertext using the reconstructed lambda (λ).
 *
 * Algorithm (matching tally_coordinator.py _decrypt_with_lambda):
 *   u   = c^λ  mod n²
 *   L_u = (u - 1) / n
 *   μ   = λ^{-1}  mod n
 *   m   = L_u * μ  mod n
 *
 * @param {string} ciphertext  – encrypted tally as decimal string
 * @param {BigInt}  lambda     – reconstructed private key component
 * @param {string}  publicKeyN – Paillier modulus N as decimal string
 * @returns {BigInt} decrypted plaintext
 */
export function paillierDecrypt(ciphertext, lambda, publicKeyN) {
  const c   = BigInt(ciphertext);
  const n   = BigInt(publicKeyN);
  const n2  = n * n;
  const lam = lambda < 0n ? ((lambda % n) + n) % n : lambda;

  const u   = modPow(c, lam, n2);
  const L_u = L(u, n);
  const mu  = modInverse(lam, n);
  const m   = (L_u * mu) % n;

  return m;
}

// ---------------------------------------------------------------------------
// High-level: full Phase 4 decryption
// ---------------------------------------------------------------------------

/**
 * Run the full threshold decryption pipeline.
 *
 * Security note: λ is reconstructed locally, used only for decryption, and
 * never leaves this function (not returned, not logged, not persisted).
 *
 * @param {string}                encryptedTally – from blockchain (decimal string)
 * @param {Array<{x,y,prime}>}    shares         – decrypted trustee share objects
 * @param {string}                publicKeyN     – Paillier N from blockchain
 * @returns {{ plaintext: string }}
 */
export function thresholdDecrypt(encryptedTally, shares, publicKeyN) {
  if (!encryptedTally || !publicKeyN) throw new Error('Missing encryptedTally or publicKeyN');
  if (!shares || shares.length === 0) throw new Error('No trustee shares provided');

  // Reconstruct λ – stays scoped to this function, never returned or exposed
  const lambda = reconstructSecret(shares);

  // Decrypt
  const plaintext = paillierDecrypt(encryptedTally, lambda, publicKeyN);

  // Return only the plaintext vote count – λ goes out of scope here
  return { plaintext: plaintext.toString() };
}

// ---------------------------------------------------------------------------
// Radix slot extraction
// ---------------------------------------------------------------------------

/**
 * Extract per-candidate vote counts from the decrypted aggregate sum (msum).
 *
 * Encoding at vote time:  plaintext = B ^ candidateIndex
 * After aggregation:      msum = sum of all plaintexts
 * Extraction:             count[i] = floor(msum / B^i) mod B
 *
 * @param {string|BigInt} msum          - Decrypted aggregate as decimal string or BigInt
 * @param {number}        numCandidates - Number of candidate slots
 * @param {string|BigInt} voteBlock     - Slot base B used at encryption time
 * @returns {Object} Map of candidateIndex (string) → vote count (number)
 */
export function extractVoteCounts(msum, numCandidates, voteBlock) {
  let tmp = BigInt(msum);
  const B = BigInt(voteBlock);
  const perCandidateVotes = {};
  for (let i = 0; i < numCandidates; i++) {
    perCandidateVotes[String(i)] = Number(tmp % B);
    tmp /= B;
  }
  return perCandidateVotes;
}

// ---------------------------------------------------------------------------
// AES-256-GCM share decryption (browser — Web Crypto API)
// Mirrors the Node.js encryptShareY() in smart-contract/shareEncryption.js
// ---------------------------------------------------------------------------

/**
 * Convert a lowercase hex string to a Uint8Array.
 * @param {string} hex
 * @returns {Uint8Array}
 */
function hexToBytes(hex) {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

/**
 * Decrypt a trustee share's `encrypted_y` payload in the browser using the Web Crypto API.
 *
 * Parameters must match the Node.js side:
 *   PBKDF2-SHA256, 100 000 iterations → AES-256-GCM, 128-bit tag
 *
 * @param {{ salt: string, nonce: string, ciphertext: string, tag: string }} encryptedY
 *        Hex-encoded fields from the trustee share JSON file.
 * @param {string} passphrase  Trustee passphrase (UTF-8)
 * @returns {Promise<string>}  Plaintext y value (large decimal integer string)
 * @throws {Error}  If passphrase is wrong (auth-tag mismatch) or data is corrupted.
 */
export async function decryptShareY(encryptedY, passphrase) {
  const enc = new TextEncoder();
  const dec = new TextDecoder();

  // 1. Import raw passphrase bytes as PBKDF2 key material
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    enc.encode(passphrase),
    { name: 'PBKDF2' },
    false,
    ['deriveBits']
  );

  // 2. Derive 256-bit AES key (same params as Node.js pbkdf2Sync)
  const salt    = hexToBytes(encryptedY.salt);
  const keyBits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: 100_000, hash: 'SHA-256' },
    keyMaterial,
    256
  );

  // 3. Import derived key as AES-GCM key
  const aesKey = await crypto.subtle.importKey(
    'raw',
    keyBits,
    { name: 'AES-GCM' },
    false,
    ['decrypt']
  );

  // 4. Web Crypto AES-GCM expects ciphertext || tag concatenated
  const ciphertext       = hexToBytes(encryptedY.ciphertext);
  const tag              = hexToBytes(encryptedY.tag);
  const ciphertextWithTag = new Uint8Array(ciphertext.length + tag.length);
  ciphertextWithTag.set(ciphertext);
  ciphertextWithTag.set(tag, ciphertext.length);

  const nonce = hexToBytes(encryptedY.nonce);

  try {
    const plaintextBuf = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: nonce, tagLength: 128 },
      aesKey,
      ciphertextWithTag
    );
    return dec.decode(plaintextBuf);
  } catch {
    throw new Error('Incorrect passphrase or corrupted share file — AES-GCM authentication failed');
  }
}

export default { reconstructSecret, paillierDecrypt, thresholdDecrypt, extractVoteCounts, decryptShareY };
