/**
 * Threshold Decryption Utility – Phase 4
 *
 * Implements:
 *  - Lagrange interpolation over integers (Shamir secret reconstruction)
 *  - Paillier homomorphic decryption using the reconstructed lambda (λ)
 *
 * All arithmetic is done with BigInt to handle 2048-bit numbers correctly.
 */

// ---------------------------------------------------------------------------
// BigInt helpers
// ---------------------------------------------------------------------------

/**
 * Fast modular exponentiation: (base ^ exp) mod modulus
 */
export function modPow(base, exp, modulus) {
  if (modulus === 1n) return 0n;
  let result = 1n;
  base = ((base % modulus) + modulus) % modulus;
  while (exp > 0n) {
    if (exp & 1n) result = (result * base) % modulus;
    exp >>= 1n;
    base = (base * base) % modulus;
  }
  return result;
}

/**
 * Extended Euclidean Algorithm – returns { gcd, x, y } such that a*x + b*y = gcd
 */
function extendedGcd(a, b) {
  if (b === 0n) return { gcd: a, x: 1n, y: 0n };
  const { gcd, x, y } = extendedGcd(b, a % b);
  return { gcd, x: y, y: x - (a / b) * y };
}

/**
 * Modular multiplicative inverse: a^-1 mod m
 * Throws if inverse does not exist.
 */
function modInverse(a, m) {
  const { gcd, x } = extendedGcd(((a % m) + m) % m, m);
  if (gcd !== 1n) throw new Error('Modular inverse does not exist');
  return ((x % m) + m) % m;
}

// ---------------------------------------------------------------------------
// Shamir Secret Reconstruction (Lagrange interpolation at x = 0)
// ---------------------------------------------------------------------------

/**
 * Reconstruct the Shamir secret from a threshold number of shares.
 *
 * Each share is an object with numeric `x`, string `y`, and optionally
 * string `prime` fields (as stored in the trustee_shares/*.json files after
 * being decrypted by decryptShareY).
 *
 * When `prime` is present (generated by the fixed backend), uses modular
 * Lagrange interpolation over GF(prime) — information-theoretically secure.
 * Falls back to rational interpolation for legacy shares without a prime.
 *
 * @param {Array<{x: number, y: string, prime?: string}>} shares
 * @returns {BigInt} reconstructed secret (lambda)
 */
export function reconstructSecret(shares) {
  if (shares.length < 2) throw new Error('Need at least 2 shares to reconstruct');

  // Convert to BigInt pairs
  const pts = shares.map(s => ({ x: BigInt(s.x), y: BigInt(s.y) }));

  // --- Modular path (secure, preferred) ---
  const primeStr = shares[0].prime;
  if (primeStr) {
    const p = BigInt(primeStr);
    let secret = 0n;

    for (let i = 0; i < pts.length; i++) {
      let num = 1n;
      let den = 1n;

      for (let j = 0; j < pts.length; j++) {
        if (i === j) continue;
        num = (num * ((0n - pts[j].x + p) % p)) % p;
        den = (den * ((pts[i].x - pts[j].x + p) % p)) % p;
      }

      const lagrange = (num * modInverse(den, p)) % p;
      secret = (secret + pts[i].y * lagrange) % p;
    }

    return secret;
  }

  // --- Legacy rational path (kept for backward compatibility) ---
  // Lagrange interpolation at x = 0 over rationals, accumulated as fractions
  // f(0) = Σ_i  y_i * Π_{j≠i} (0 - x_j) / (x_i - x_j)
  let numeratorAcc = 0n;
  let denominatorAcc = 1n;

  for (let i = 0; i < pts.length; i++) {
    let num = pts[i].y;   // y_i
    let den = 1n;

    for (let j = 0; j < pts.length; j++) {
      if (i === j) continue;
      num *= (0n - pts[j].x);   // × (-x_j)
      den *= (pts[i].x - pts[j].x); // × (x_i - x_j)
    }

    // Accumulate: acc = acc + num/den
    // Using cross-multiplication: (a/b) + (c/d) = (a*d + c*b) / (b*d)
    numeratorAcc = numeratorAcc * den + num * denominatorAcc;
    denominatorAcc = denominatorAcc * den;
  }

  // The secret is the integer result of numeratorAcc / denominatorAcc
  if (denominatorAcc === 0n) throw new Error('Degenerate shares: denominator is zero');
  if (numeratorAcc % denominatorAcc !== 0n) {
    throw new Error('Share reconstruction yielded non-integer result – shares may be corrupt');
  }

  return numeratorAcc / denominatorAcc;
}

// ---------------------------------------------------------------------------
// Paillier Decryption
// ---------------------------------------------------------------------------

/**
 * Paillier L-function: L(u) = (u - 1) / n
 */
function L(u, n) {
  return (u - 1n) / n;
}

/**
 * Decrypt a Paillier ciphertext using the reconstructed lambda (λ).
 *
 * Algorithm (matching tally_coordinator.py _decrypt_with_lambda):
 *   u   = c^λ  mod n²
 *   L_u = (u - 1) / n
 *   μ   = λ^{-1}  mod n
 *   m   = L_u * μ  mod n
 *
 * @param {string} ciphertext  – encrypted tally as decimal string
 * @param {BigInt}  lambda     – reconstructed private key component
 * @param {string}  publicKeyN – Paillier modulus N as decimal string
 * @returns {BigInt} decrypted plaintext
 */
export function paillierDecrypt(ciphertext, lambda, publicKeyN) {
  const c   = BigInt(ciphertext);
  const n   = BigInt(publicKeyN);
  const n2  = n * n;
  const lam = lambda < 0n ? ((lambda % n) + n) % n : lambda;

  const u   = modPow(c, lam, n2);
  const L_u = L(u, n);
  const mu  = modInverse(lam, n);
  const m   = (L_u * mu) % n;

  return m;
}

// ---------------------------------------------------------------------------
// Ping-Pong Threshold Decryption Math
// ---------------------------------------------------------------------------

/**
 * Trustee computation: Partial Decryption
 * PD_i = C^{s_i} mod n^2
 * @param {string} encryptedTally (C)
 * @param {string|BigInt} shareY (s_i)
 * @param {string} publicKeyN (n)
 * @returns {string} PD_i as string
 */
export function computeTrusteePartialDecryption(encryptedTally, shareY, publicKeyN) {
  const c = BigInt(encryptedTally);
  const s = BigInt(shareY);
  const n = BigInt(publicKeyN);
  const n2 = n * n;
  
  // To evaluate PD_i = C^{s_i} mod n^2
  // We handle negative s properly just in case, though they should be positive.
  let p = s;
  let base = c;
  if (p < 0n) {
    p = -p;
    base = modInverse(base, n2);
  }
  
  const pd = modPow(base, p, n2);
  return pd.toString();
}

/**
 * Organizer computation: Combine Partial Decryptions
 * Uses Lagrange interpolation over integers.
 * @param {Array<{x: number, pd: string}>} partialDecryptions 
 * @param {string} publicKeyN (n)
 * @returns {string} Fully decrypted plaintext M
 */
export function combinePartialDecryptions(partialDecryptions, publicKeyN) {
  if (partialDecryptions.length < 2) throw new Error('Need at least 2 partial decryptions');

  const n = BigInt(publicKeyN);
  const n2 = n * n;
  
  // Convert inputs
  const pds = partialDecryptions.map(p => ({ x: BigInt(p.x), pd: BigInt(p.pd) }));

  // 1. Calculate Lagrange weights L_i(0) as fractions: N_i / D_i
  const weights = [];
  for (let i = 0; i < pds.length; i++) {
    let num = 1n;
    let den = 1n;
    for (let j = 0; j < pds.length; j++) {
      if (i === j) continue;
      num *= (0n - pds[j].x);
      den *= (pds[i].x - pds[j].x);
    }
    weights.push({ num, den });
  }

  // 2. Compute common Delta (product of absolute values of all D_i)
  // This guarantees integer exponents for everyone.
  let delta = 1n;
  for (const w of weights) {
    const absD = w.den < 0n ? -w.den : w.den;
    delta *= absD;
  }

  // 3. Compute V = \prod PD_i ^ { \lambda_i } mod n^2
  let V = 1n;
  for (let i = 0; i < pds.length; i++) {
    const { num, den } = weights[i];
    // lambda_i = (Delta / D_i) * N_i
    const lambda_i = (delta / den) * num;
    
    let base = pds[i].pd;
    let exp = lambda_i;
    
    if (exp < 0n) {
      exp = -exp;
      base = modInverse(base, n2);
    }
    
    const term = modPow(base, exp, n2);
    V = (V * term) % n2;
  }

  // 4. Extract plaintext
  // Apply L-function: L(V) = (V - 1) / n
  // L(V) equals (m * Delta) mod n
  
  // Since V = 1 + n * m * \Delta_S mod n^2, handling negative (V-1)/n in case JS gives negative mod
  let V_minus_1 = V - 1n;
  if (V_minus_1 < 0n) V_minus_1 += n2;
  
  let L_val = V_minus_1 / n;
  L_val = L_val % n; 
  if (L_val < 0n) L_val += n;

  // 5. Final multiplication by Delta^-1 mod n
  const deltaInv = modInverse(delta, n);
  const m = (L_val * deltaInv) % n;

  return m.toString();
}

// ---------------------------------------------------------------------------
// High-level: full Phase 4 decryption
// ---------------------------------------------------------------------------

/**
 * Run the full threshold decryption pipeline.
 *
 * Security note: λ is reconstructed locally, used only for decryption, and
 * never leaves this function (not returned, not logged, not persisted).
 *
 * @param {string}                encryptedTally – from blockchain (decimal string)
 * @param {Array<{x,y,prime}>}    shares         – decrypted trustee share objects
 * @param {string}                publicKeyN     – Paillier N from blockchain
 * @returns {{ plaintext: string }}
 */
export function thresholdDecrypt(encryptedTally, shares, publicKeyN) {
  if (!encryptedTally || !publicKeyN) throw new Error('Missing encryptedTally or publicKeyN');
  if (!shares || shares.length === 0) throw new Error('No trustee shares provided');

  // Reconstruct λ – stays scoped to this function, never returned or exposed
  const lambda = reconstructSecret(shares);

  // Decrypt
  const plaintext = paillierDecrypt(encryptedTally, lambda, publicKeyN);

  // Return only the plaintext vote count – λ goes out of scope here
  return { plaintext: plaintext.toString() };
}

// ---------------------------------------------------------------------------
// Radix slot extraction
// ---------------------------------------------------------------------------

/**
 * Extract per-candidate vote counts from the decrypted aggregate sum (msum).
 *
 * Encoding at vote time:  plaintext = B ^ candidateIndex
 * After aggregation:      msum = sum of all plaintexts
 * Extraction:             count[i] = floor(msum / B^i) mod B
 *
 * @param {string|BigInt} msum          - Decrypted aggregate as decimal string or BigInt
 * @param {number}        numCandidates - Number of candidate slots
 * @param {string|BigInt} voteBlock     - Slot base B used at encryption time
 * @returns {Object} Map of candidateIndex (string) → vote count (number)
 */
export function extractVoteCounts(msum, numCandidates, voteBlock) {
  let tmp = BigInt(msum);
  const B = BigInt(voteBlock);
  
  if (tmp.toString().length > (numCandidates * B.toString().length + 5)) {
    throw new Error('CRITICAL DECRYPTION FAILURE: The decrypted result is mathematically garbage (' + tmp.toString().length + ' digits). This occurs because one or more Trustees uploaded the wrong share file (e.g. uploading trustee_1 on Trustee 2 account), corrupting the Secret Sharing interpolation.');
  }

  const perCandidateVotes = {};
  for (let i = 0; i < numCandidates; i++) {
    perCandidateVotes[String(i)] = Number(tmp % B);
    tmp /= B;
  }
  return perCandidateVotes;
}

// ---------------------------------------------------------------------------
// AES-256-GCM share decryption (browser — Web Crypto API)
// Mirrors the Node.js encryptShareY() in smart-contract/shareEncryption.js
// ---------------------------------------------------------------------------

/**
 * Convert a lowercase hex string to a Uint8Array.
 * @param {string} hex
 * @returns {Uint8Array}
 */
function hexToBytes(hex) {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

/**
 * Decrypt a trustee share's `encrypted_y` payload in the browser using the Web Crypto API.
 *
 * Parameters must match the Node.js side:
 *   PBKDF2-SHA256, 100 000 iterations → AES-256-GCM, 128-bit tag
 *
 * @param {{ salt: string, nonce: string, ciphertext: string, tag: string }} encryptedY
 *        Hex-encoded fields from the trustee share JSON file.
 * @param {string} passphrase  Trustee passphrase (UTF-8)
 * @returns {Promise<string>}  Plaintext y value (large decimal integer string)
 * @throws {Error}  If passphrase is wrong (auth-tag mismatch) or data is corrupted.
 */
export async function decryptShareY(encryptedY, passphrase) {
  const enc = new TextEncoder();
  const dec = new TextDecoder();

  // 1. Import raw passphrase bytes as PBKDF2 key material
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    enc.encode(passphrase),
    { name: 'PBKDF2' },
    false,
    ['deriveBits']
  );

  // 2. Derive 256-bit AES key (same params as Node.js pbkdf2Sync)
  const salt    = hexToBytes(encryptedY.salt);
  const keyBits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: 100_000, hash: 'SHA-256' },
    keyMaterial,
    256
  );

  // 3. Import derived key as AES-GCM key
  const aesKey = await crypto.subtle.importKey(
    'raw',
    keyBits,
    { name: 'AES-GCM' },
    false,
    ['decrypt']
  );

  // 4. Web Crypto AES-GCM expects ciphertext || tag concatenated
  const ciphertext       = hexToBytes(encryptedY.ciphertext);
  const tag              = hexToBytes(encryptedY.tag);
  const ciphertextWithTag = new Uint8Array(ciphertext.length + tag.length);
  ciphertextWithTag.set(ciphertext);
  ciphertextWithTag.set(tag, ciphertext.length);

  const nonce = hexToBytes(encryptedY.nonce);

  try {
    const plaintextBuf = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: nonce, tagLength: 128 },
      aesKey,
      ciphertextWithTag
    );
    return dec.decode(plaintextBuf);
  } catch {
    throw new Error('Incorrect passphrase or corrupted share file — AES-GCM authentication failed');
  }
}

/**
 * Generate a random BigInt of specified bit length
 */
function randomBigInt(bits) {
  const bytes = Math.ceil(bits / 8);
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  let res = 0n;
  for (let i = 0; i < bytes; i++) res = (res << 8n) | BigInt(buf[i]);
  const extra = (bytes * 8) - bits;
  if (extra > 0) res = res >> BigInt(extra);
  return res;
}

/**
 * Generate a Non-Interactive Chaum-Pedersen Zero-Knowledge Proof.
 * Proves that pd_i = c^{s_i} mod n^2 and V_i = v^{s_i} mod n^2 share the same s_i.
 * Uses integer arithmetic for z to prevent statistical leakage since the group order is unknown.
 */
export async function generateDecryptionProof(cHex, s_iHex, vHex, V_iHex, nHex) {
  const c = BigInt(cHex);
  const s_i = BigInt(s_iHex);
  const v = BigInt(vHex);
  const V_i = BigInt(V_iHex);
  const n = BigInt(nHex);
  const n2 = n * n;

  // w needs to be strictly larger than e * s_i to prevent leakage.
  // s_i is up to ~2048 bits. e is 256 bits. Adding 80 bits for statistical security = 2384. 
  // 3000 bits is safe.
  const w = randomBigInt(3000);

  const A1 = modPow(v, w, n2);
  const A2 = modPow(c, w, n2);

  let p = s_i;
  let basec = c;
  if (p < 0n) {
      p = -p;
      basec = modInverse(basec, n2);
  }
  const pd_i = modPow(basec, p, n2);

  const msg = v.toString() + V_i.toString() + c.toString() + pd_i.toString() + A1.toString() + A2.toString();
  const encoder = new TextEncoder();
  const data = encoder.encode(msg);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  const e = BigInt('0x' + hashHex);

  const z = w + (e * s_i);

  return {
    e: e.toString(),
    z: z.toString(),
    pd_i: pd_i.toString()
  };
}

/**
 * Verify heavily rigorous Chaum-Pedersen proofs published by the Trustees.
 * Protects Combiners/Organizers from a Denial-of-Service or silent data corruption attack.
 */
export async function verifyDecryptionProof(cHex, vHex, V_iHex, pd_iHex, eStr, zStr, nHex) {
  try {
    const c = BigInt(cHex);
    const v = BigInt(vHex);
    const V_i = BigInt(V_iHex);
    const pd = BigInt(pd_iHex);
    const e = BigInt(eStr);
    const z = BigInt(zStr);
    const n = BigInt(nHex);
    const n2 = n * n;

    // A1 = (v^z) * (V_i^{-e}) mod n^2
    const v_z = modPow(v, ((z % n2) + n2) % n2, n2); // For bases, exponent can just be calculated directly? No, z is over the integers, we cannot reduce z mod n2 because order of v is unknown!
    // Wait, modPow applies repeated squaring on the EXPLICIT integer z. That is completely valid.
    const v_z_raw = modPow(v, z, n2);
    
    // Using modInverse(V_i, n2)^e or modPow(V_i, e, n2) inverted
    let Vi_e = modPow(V_i, e, n2);
    let Vi_e_inv = modInverse(Vi_e, n2);
    let A1 = (v_z_raw * Vi_e_inv) % n2;

    // A2 = (c^z) * (pd_i^{-e}) mod n^2
    let c_z_raw = modPow(c, z, n2);
    let pd_e = modPow(pd, e, n2);
    let pd_e_inv = modInverse(pd_e, n2);
    let A2 = (c_z_raw * pd_e_inv) % n2;

    const msg = v.toString() + V_i.toString() + c.toString() + pd.toString() + A1.toString() + A2.toString();
    const encoder = new TextEncoder();
    const data = encoder.encode(msg);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    const eCalc = BigInt('0x' + hashHex);

    return eCalc === e;
  } catch (error) {
    console.error("ZKP verification internally failed:", error);
    return false;
  }
}

export default { reconstructSecret, paillierDecrypt, thresholdDecrypt, extractVoteCounts, decryptShareY, modPow, computeTrusteePartialDecryption, combinePartialDecryptions, generateDecryptionProof, verifyDecryptionProof };

